version: '3'

services:
  app:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - ${PORT:-3000}
    depends_on:
      - pg
    command: yarn start
    env_file: .env

  pg:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DATABASE:  test

volumes:
  node_modules:
  postgres:
    